[package]
name = "screenplay-scripted"
version = "0.1.0"
authors = [ "carlxw <https://www.carlxw.dev>" ]
description = "Write Oscar-formatted TV or movie scripts drafts with handy helper functions."
entrypoint = "lib.typ"

categories = [ "text" ]
disciplines = [ "film", "theater" ]
keywords = ["film", "movie", "screenplay", "script", "tv", "show"]

repository = "https://www.github.com/carlxw/screenplay-scripted"
licnese = "MIT-0"

[template]
path = "template"
thumbnail = "screenplay-scripted.png"
entrypoint = "example.typ"
